### ISSUE TITLE
Demon Fire - Illidan Event.

### ISSUE THREAD

**Issue by Ulduar** [scriptdev2/scriptdev2-tbc#27]
https://github.com/ACID-Scripts/TBC/commit/bd0e6cb67f73e6a4bdc08c48f45138f19ef20414
http://www.wowhead.com/npc=23069/demon-fire
Should have react state passive.
Suggest delete EAI script and add in SD2 script.
Or delete EAI script and add aura in creature_template_addon and NullAI in database.
Or add SET_REACT_STATE_PASSIVE ACTION in EAI.

**Comment by xfurry** [comment]
Or we can use creature_template_addon.

**Comment by Ulduar** [comment]
``` QUOTE
Or delete EAI script and add aura in creature_template_addon and NullAI in database.
```
I already wrote.

**Comment by Ulduar** [comment]
``` SQL
DELETE FROM creature_template_addon WHERE entry = 23069;
INSERT INTO creature_template_addon (entry, auras) VALUES 
(23069,,40029);
```
``` SQL
UPDATE `creature_template` SET `AIName` = 'NullAI', `ScriptName` = '' WHERE `entry` IN (23069);
DELETE FROM `creature_ai_scripts` WHERE `creature_id` = 23069;
```

**Comment by Ulduar** [comment]
Issue close and transfer in https://github.com/unified-db/Database/issues/86
Please send notification TBC-DB developer, YTDB and UDB developers. Thanks.

**Comment by xfurry** [comment]
If you have creature_template_addon you don't need NullAI as the creature already has the right flags and behavior.

**Comment by Ulduar** [comment]
``` QUOTE
If you have creature_template_addon you don't need NullAI as the creature already has the right flags and behavior.
```
No. NullAI need, how additional insurance. If npc has AggressorAI and deal damage, he will attack you and beat auto attack. That should not be. I'll tested already, so would not create Issues.

**Comment by xfurry** [comment]
> If npc has AggressorAI and deal damage, he will attack you and beat auto attack.

It shouldn't happen if the creature is not_selectable. If it's not and the unit flags are right then we need NullAI

**Comment by Ulduar** [comment]
not_selectable can not help. CAN NOT HELP ME. I'll tested and npc aggro on me if deal damage with auras.

**Comment by xfurry** [comment]
@Ulduar I'm afraid you are totally wrong....
Creature 23069 has unit flag 33554432 (not_selectable).

https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Creature.cpp#L1922
https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Creature.cpp#L1957
This will show exactly what this will do -> hence the creature won't attack.

However.
Because the spell that is cast deals damage, the creature will override those functions and be set in combat and then instantly evade.
This is the reason why the aura is removed and we need creature_template_addon. There are lot of creatures like this, that have aura in c_t_a but they won't attack because of the unit flag.
